version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/
hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
